name: Build Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm install

      - run: npm run build

      - run: npx cap sync android

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: android-actions/setup-android@v3

      - run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease

      - uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: android/app/build/outputs/apk/release/app-release.apk